FROM python:3.11-alpine3.21

WORKDIR /app

# 1. تحديث كافة حزم النظام إلى أحدث إصدارات آمنة
RUN apk update && apk upgrade --no-cache && \
    apk add --no-cache gcc musl-dev postgresql-dev

COPY backend/requirements.txt .

# 2. تحديث pip و setuptools والخزم الخالية من الثغرات
RUN pip install --no-cache-dir --upgrade pip setuptools wheel && \
    pip install --no-cache-dir -r requirements.txt

COPY . .

RUN cp -r frontend/templates backend/templates
RUN cp -r frontend/static backend/static

ENV PYTHONPATH=/app

CMD ["flask", "--app", "backend/server.py", "run", "--host=0.0.0.0", "--port=5000"]
