FROM python:3.12-slim
 
WORKDIR /app
 
COPY . .
 
RUN pip install --no-cache-dir --upgrade pip setuptools wheel && \
RUN pip install --no-cache-dir -r requirements.txt 
RUN cp -r frontend/templates backend/templates
RUN cp -r frontend/static backend/static
 
ENV PYTHONPATH=/app
 
CMD ["flask", "--app", "backend/server.py", "run", "--host=0.0.0.0", "--port=5000"]
