FROM python:3.11-alpine3.18

WORKDIR /app

# Alpine uses apk instead of apt
RUN apk add --no-cache gcc musl-dev postgresql-dev

COPY backend/requirements.txt .
RUN pip install --no-cache-dir --upgrade pip setuptools wheel && \
    pip install --no-cache-dir -r requirements.txt

COPY . .

RUN cp -r frontend/templates backend/templates
RUN cp -r frontend/static backend/static

ENV PYTHONPATH=/app

CMD ["flask", "--app", "backend/server.py", "run", "--host=0.0.0.0", "--port=5000"]
