name: Expense Tracker CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io

jobs:
  lint:
    name: Code Quality Check (Linting)
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run Flake8 Lint
        run: |
          flake8 backend --count --select=E9,F63,F7,F82 --show-source --statistics || true

  build-and-push:
    name: Docker Build & Push
    needs: lint
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Convert Owner Name to Lowercase
        run: |
          echo "OWNER_LOWER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build and Push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.OWNER_LOWER }}/expense-tracker-backend:latest
            ghcr.io/${{ env.OWNER_LOWER }}/expense-tracker-backend:${{ github.sha }}

      - name: Build and Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.OWNER_LOWER }}/expense-tracker-frontend:latest
            ghcr.io/${{ env.OWNER_LOWER }}/expense-tracker-frontend:${{ github.sha }}
